version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      # Ensure that the variables in .env match the same variables in devcontainer.json
      - ./.env
    volumes:
      - ../..:/workspaces:cached
    ports:
      - "3000"
    command: sleep infinity
    environment:
      GH_TOKEN: ${GH_TOKEN}
