name: Build and Release

on:
  release:
    types: [published]

jobs:
  build-matrix:
    name: Build Electron App (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            build_script: build:linux
            upload_pattern: 'dist/*.AppImage'
          - os: macos-latest
            build_script: build:mac
            upload_pattern: 'dist/*.dmg'
          - os: windows-latest
            build_script: build:win
            upload_pattern: 'dist/*.exe'

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build Electron app
        run: npm run ${{ matrix.build_script }}

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.upload_pattern }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
